[cite_start]name: Flujo_trabajo # [cite: 678]

[cite_start]on: # [cite: 680]
  [cite_start]push: # [cite: 681]
    branches:
      - [cite_start]main # [cite: 683]

[cite_start]jobs: # [cite: 686]
  [cite_start]validar-auth: # [cite: 688]
    [cite_start]runs-on: ubuntu-latest # [cite: 690]
    [cite_start]steps: # [cite: 691]
      - [cite_start]name: Checkout code # [cite: 694]
        [cite_start]uses: actions/checkout@v3 # [cite: 695]

      - [cite_start]name: Use Personal Access Token # [cite: 731]
        run: | [cite_start]# [cite: 733]
          curl -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
               -H "Accept: application/vnd.github.v3+json" \
               [cite_start]https://api.github.com/user/repos # [cite: 734, 735, 736]